# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/timovi/Insignia_Delta3/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),Insignia_Delta3)

endif
